{% set name = "dm-tree" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a4c7db3d3935a5a2d5e4b383fc26c6b0cd6f78c6d4605d3e7b518800ecd5342b
  patches:
    - patches/0001-allow-cmake-args-from-env.patch

build:
  number: 1
  skip: true  # [py<310]
  script_env:                                # [win]
    - CMAKE_GENERATOR=Visual Studio 16 2019  # [win]
  script: |
    export CMAKE_ARGS="-DUSE_SYSTEM_ABSEIL=ON -DCMAKE_CXX_STANDARD=17 -DUSE_SYSTEM_PYBIND11=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCMAKE_MESSAGE_LOG_LEVEL=DEBUG"  # [not win]
    set "CMAKE_ARGS=-DUSE_SYSTEM_ABSEIL=ON -DCMAKE_CXX_STANDARD=17 -DUSE_SYSTEM_PYBIND11=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCMAKE_MESSAGE_LOG_LEVEL=DEBUG"  # [win]
    {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make      # [not win]
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - libabseil {{ libabseil }}
    - pip
    - pybind11
    - setuptools
    - wheel
  run:
    - python
    - absl-py >=0.6.1
    - attrs >=18.2.0
    - numpy >=1.21
    - wrapt >=1.11.2

test:
  imports:
    - tree
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest --pyargs tree

about:
  home: https://github.com/deepmind/tree
  summary: Tree is a library for working with nested data structures.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    tree is a library for working with nested data structures.
    In a way, tree generalizes the builtin map function which only supports flat sequences, and allows to apply a function to each "leaf" preserving the overall structure.

  doc_url: https://tree.readthedocs.io
  dev_url: https://github.com/deepmind/tree

extra:
  recipe-maintainers:
    - vnlitvinov
  skip-lints:
    - missing_doc_source_url
    - missing_license_url
